# Generated by Django 5.0.6 on 2026-01-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_address_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
    ]
