# Generated by Django 6.0 on 2026-01-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ingredient_dishingredient'),
        ('users', '0004_customuser_balance_customuser_bonus_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='allergens',
            field=models.ManyToManyField(blank=True, help_text='Отметьте ингредиенты-аллергены', to='orders.ingredient', verbose_name='Аллергены'),
        ),
    ]
