# Generated by Django 6.0 on 2026-01-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_visible_to_customer',
            field=models.BooleanField(default=True, verbose_name='Виден ученику'),
        ),
    ]
