# Generated by Django 5.2.9 on 2026-01-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_visible_to_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('ready', 'Готово'), ('delivered', 'забран'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
