# Generated by Django 6.0 on 2026-01-23 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComboSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название набора')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_sets', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Комбо-набор',
                'verbose_name_plural': 'Комбо-наборы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('preparing', 'Готовится'), ('ready', 'Готово'), ('picked_up', 'Получен')], default='preparing', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_orders', to=settings.AUTH_USER_MODEL, verbose_name='Ученик')),
                ('combo_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='orders.comboset', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Заказ комбо-набора',
                'verbose_name_plural': 'Заказы комбо-наборов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComboItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.dish', verbose_name='Блюдо')),
                ('combo_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.comboset', verbose_name='Набор')),
            ],
            options={
                'verbose_name': 'Элемент комбо-набора',
                'verbose_name_plural': 'Элементы комбо-наборов',
            },
        ),
    ]
