# Generated by Django 6.0 on 2026-01-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_comboset_comboorder_comboitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание платежа'),
        ),
    ]
