# Generated by Django 6.0 on 2026-01-24 08:09

from django.db import migrations

def update_existing_payments(apps, schema_editor):
    Payment = apps.get_model('orders', 'Payment')

def reverse_update(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_payment_order'),
    ]

    operations = [
    ]
