# Generated by Django 6.0 on 2026-01-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_update_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboset',
            name='max_orders',
            field=models.PositiveIntegerField(default=1, verbose_name='Максимальное количество заказов'),
        ),
        migrations.AddField(
            model_name='comboset',
            name='orders_used',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Использовано заказов'),
        ),
    ]
