# Generated by Django 6.0 on 2026-01-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_comboset_max_orders_comboset_orders_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comboset',
            name='max_orders',
            field=models.PositiveIntegerField(default=1, help_text='Сколько раз можно заказать этот набор', verbose_name='Максимальное количество заказов'),
        ),
        migrations.AlterField(
            model_name='comboset',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за один набор'),
        ),
    ]
