# Generated by Django 5.0.6 on 2026-01-29 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_comboset_max_orders_alter_comboset_total_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('preparing', 'Готовится'), ('ready', 'Готово'), ('out_of_stock', 'Нет в наличии')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='IngredientStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущее количество')),
                ('min_quantity', models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Минимальное количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('last_restocked', models.DateTimeField(auto_now=True, verbose_name='Последнее пополнение')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='orders.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Запас ингредиента',
                'verbose_name_plural': 'Запасы ингредиентов',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='PreparedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество готовых')),
                ('max_quantity', models.PositiveIntegerField(default=20, verbose_name='Максимальное количество')),
                ('prepared_at', models.DateTimeField(auto_now_add=True, verbose_name='Время приготовления')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepared_items', to='orders.dish', verbose_name='Блюдо')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто приготовил')),
            ],
            options={
                'verbose_name': 'Готовое блюдо',
                'verbose_name_plural': 'Готовые блюда',
                'ordering': ['dish__name'],
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('restock', 'Пополнение'), ('usage', 'Использование'), ('adjustment', 'Корректировка'), ('waste', 'Списание (брак)'), ('request', 'Запрос на пополнение')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Изменение количества')),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='orders.ingredient')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
            ],
            options={
                'verbose_name': 'История запасов',
                'verbose_name_plural': 'История запасов',
                'ordering': ['-created_at'],
            },
        ),
    ]
