# Generated by Django 5.0.6 on 2026-01-29 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_orderitem_status_ingredientstock_prepareddish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость операции'),
        ),
        migrations.CreateModel(
            name='IngredientCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость за единицу (руб)')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='orders.ingredient', verbose_name='Ингредиент')),
            ],
            options={
                'verbose_name': 'Стоимость ингредиента',
                'verbose_name_plural': 'Стоимость ингредиентов',
            },
        ),
    ]
