# Generated by Django 5.0.6 on 2026-02-05 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_stockhistory_total_cost_ingredientcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='comboorder',
            name='main_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combo_order_ref', to='orders.order', verbose_name='Основной заказ'),
        ),
    ]
